### PR TITLE
ActionMenu falsy value bugfix

### LINKED ISSUE #906: 🐛 [BUG] - ActionMenu ignores items whose value is falsy
### Describe the bug

In the `ActionMenu` component, selection is ignored if the item's value is falsy (including here where it's intentionally `0`). I understand we might have wanted [this check](https://github.com/primer/brand/blob/main/packages/react/src/ActionMenu/ActionMenu.tsx#L169) to filter out invalid items so, if kept, maybe checking `newValue` against `undefined` instead would do? We might intentionally want to use `null` or `false` as values.

This is currently non-blocking for my use case since I'm working with numeric values (see ugly temp workaround below), but it might be different for a user who needs to use `null` or `false` for example. Thanks.

```
onToggle(String(+newValue - 1))

...

<ActionMenu.Item value={item.value + 1} ... />
```

### Reproduction steps

```bash
1. Setup an `ActionMenu` component with two items: one whose value is falsy (including but not limited to `undefined`), the other not.
2. Open the browser and attempt to select the first item in the menu
3. Observe that it cannot be selected
```

### Expected behavior

```bash
`ActionMenu` items should be selectable even if they have a falsy value, unless it is specifically `undefined`.
```

### Screenshots

https://github.com/user-attachments/assets/468ea74b-143f-45f4-9369-e3840dbe222b

### Browsers

Chrome

### OS

Mac

### PR DESCRIPTION
**Pull request by joshfarrant**
## Summary

Removes check for truthiness in `handleItemSelection` in `ActionMenu.tsx` to allow falsy values to trigger item selection callback.

## List of notable changes:

- `ActionMenu.tsx`: Removed check for truthiness in `handleItemSelection` to allow falsy values to trigger item selection callback.
- `ActionMenu.test.tsx`: Added a test to assert that falsy items can be selected

## Steps to test:

1. Open [the ActionMenu Docs](https://primer-f49b2ea768-26139705.drafts.github.io/brand/components/ActionMenu)
2. Edit the first example to set one of the values to `""`
3. Open the ActionMenu and click on the item associated with that value
4. Observe that the `onSelect` callback is called and triggers an alert.

## Supporting resources (related issues, external links, etc):

- 🔗 [Link to docs](https://primer-f49b2ea768-26139705.drafts.github.io/brand/components/ActionMenu)
- Closes #906 

## Contributor checklist:

- [x] All new and existing CI checks pass
- [x] Tests prove that the feature works and covers both happy and unhappy paths
- [x] Any drop in coverage, breaking changes or regressions have been documented above
- [x] UI Changes contain new visual snapshots (generated by adding `update snapshots` label to the PR)
- [x] All developer debugging and non-functional logging has been removed
- [x] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

### CODE REVIEW

File: packages/react/src/ActionMenu/ActionMenu.tsx [hunk 1]
```diff
@@ -166,11 +166,9 @@ const _ActionMenuRoot = memo(
...
     const handleItemSelection = useCallback(
       (newValue: string) => {
-        if (newValue) {
-          handleOnSelect(newValue)
-          toggleMenu()
-          anchorElementRef.current?.focus()
-        }
+        handleOnSelect(newValue)
+        toggleMenu()
+        anchorElementRef.current?.focus()
```
Comment (rezrah) [inline packages/react/src/ActionMenu/ActionMenu.tsx:171]: Do we need to remove the guard entirely if we want to only allow "" values to pass through? Could we continue to guard against other falsy values?

Something like:

```suggestion
        if (newValue || newValue === "") {
          handleOnSelect(newValue)
          toggleMenu()
          anchorElementRef.current?.focus()
        }
```

Comment (joshfarrant) [reply packages/react/src/ActionMenu/ActionMenu.tsx:171]: It's a good spot, and I did have that at first, however I noticed that it was a bit redundant as `newValue`'s type is a (non-optional) string, so the only scenario in which it can ever be falsy is when it equals `""`. I didn't want to add redundant checks in that TypeScript already covered for us, so I ended up with this.

Comment (joshfarrant) [reply packages/react/src/ActionMenu/ActionMenu.tsx:171]: > Curious what the use-cases are for allowing all falsy values through otherwise.

In reality I'm not sure there's ever a situation where a falsy value is the only way to accomplish something, but the current behaviour does feel a bit counterintuitive.

More context on the specific use-case that prompted this here https://github.com/primer/brand/issues/906

Comment (rezrah) [reply packages/react/src/ActionMenu/ActionMenu.tsx:171]: Thanks, I've just looked and the original issue and wondering if this is even feasible.

We can't allow falsy values because the selected text is needed for the button label. This is why the guard is likely there to begin with. 

https://github.com/user-attachments/assets/34e67ec3-7eef-46d8-b20c-ff07ca8b1876

Comment (joshfarrant) [reply packages/react/src/ActionMenu/ActionMenu.tsx:171]: From what I can tell, the `ActionMenu` doesn't manage the Button label. The label gets passed in as a child to `<ActionMenu.Button>` so it's up to the implementor to define. In many of our Storybook and Docs examples we have added some state to the rendered example to implement the behaviour shown in your video above, but this functionality is not actually a part of the component itself.

Assuming `ActionMenu` is intended to function in the same way as an HTML `<select>` element, then we should treat a value of `""` in the same way as any other string since `<select>` doesn't discriminate between `""` and any other string. In the case of `<select>`, using an empty string as a value doesn't seem to be an uncommon pattern.

Comment (rezrah) [reply packages/react/src/ActionMenu/ActionMenu.tsx:171]: Ah yes, just saw that thanks. That's fine then. I guess it's okay to make this change, but I still can't really see the use-case for allowing null or undefined values through like this. I guess it means that the user has to mitigate those scenario's where data is from unreliable sources themselves?

Comment (joshfarrant) [reply packages/react/src/ActionMenu/ActionMenu.tsx:171]: Yea potentially.

Equally we could approach the question from the other side and ask if there's a good reason that we _should_ impose restrictions on the strings that are passed. Maybe there's no situation where passing an empty value is the _only_ way to make something work, but it seems reasonable that we offer that flexibility to consumers in case that's the approach they want to take.

Just to confirm too; null or undefined values will be flagged by TypeScript, the only behaviour that is modified by this PR is specifically the `value=""` scenario.

Comment (rezrah) [reply packages/react/src/ActionMenu/ActionMenu.tsx:171]: I see 🤔 PB does need to work in non-TS contexts though that don't have type inference. Want to make sure we're not making assumptions about that. But regardless, I agree with:

> it seems reasonable that we offer that flexibility to consumers in case that's the approach they want to take

👍

**Review by rezrah — APPROVED** [review]
