### PR TITLE
Prose list style image fix

### LINKED ISSUE #455: 🐛 [BUG] - `Prose`'s unordered lists do not play well with dark mode
### Describe the bug

Hey folks! I just discovered a possible issue with `Prose`, unordered lists, and dark mode. The list symbol always uses black color, even if wrapped with a dark mode provider.

### Reproduction steps

1. Go to https://codepen.io/sergioalvz/pen/ExGrxXb?editors=1010
2. See the result

### Expected behavior

I would expect the list symbol to use white color.

### Screenshots

Proof of bad behavior

### Browsers

Chrome

### OS

Mac

### PR DESCRIPTION
**Pull request by joseph-lozano**
## Summary

Fixes #455 

Namely, in dark mode. Prose unordered list elements will have a `white` dash instead of a black one.

## List of notable changes:

Prose's un-ordered list style now works nicely in dark mode

## What should reviewers focus on?

- Check dark and light colors.

## Steps to test:

1. You can view the prose in a dark theme under the `components-prose--unordered-list` story

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [x] New visual snapshots have been generated / updated for any UI changes
- [x] All developer debugging and non-functional logging has been removed
- [x] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

> Please try to provide before and after screenshots or videos

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

CleanShot 2023-10-16 at 09 07 21@2x

 </td>
<td valign="top">

CleanShot 2023-10-16 at 09 08 27@2x

</td>
</tr>
</table>

### CODE REVIEW

File: packages/design-tokens/src/tokens/functional/components/prose/colors.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+module.exports = {
+  brand: {
+    Prose: {
+      listStyleImageUrl: {
```
Comment (joseph-lozano) [inline packages/design-tokens/src/tokens/functional/components/prose/colors.js:4]: Would like some input as to what a good name for this value should be. Any thoughts @rezrah ?

Comment (rezrah) [reply packages/design-tokens/src/tokens/functional/components/prose/colors.js:4]: How about `--brand-Prose-unorderedList-item-bgUrl`

Comment (joseph-lozano) [reply packages/design-tokens/src/tokens/functional/components/prose/colors.js:4]: `bg` I don't think is quite right, as it isn't a background.

Comment (rezrah) [reply packages/design-tokens/src/tokens/functional/components/prose/colors.js:4]: Fair, `imageUrl` should be fine

File: packages/design-tokens/src/tokens/functional/components/prose/colors.js [hunk 2]
```diff
@@ -0,0 +1,12 @@
+module.exports = {
+  brand: {
+    Prose: {
+      imageUrl: {
+        default: {
+          value: `url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' aria-hidden='true' focusable='false' role='img' viewBox='0 -3 16 16' width='16' height='16' fill='black' style='display: inline-block; vertical-align: text-bottom; overflow: visible;'%3e%3cpath d='M2 7.75A.75.75 0 0 1 2.75 7h10a.75.75 0 0 1 0 1.5h-10A.75.75 0 0 1 2 7.75Z'%3e%3c/path%3e%3c/svg%3e ")`,
```
Comment (joseph-lozano) [inline packages/design-tokens/src/tokens/functional/components/prose/colors.js:6]: **TODO**: This should be gray-9, not black.

Comment (joseph-lozano) [reply packages/design-tokens/src/tokens/functional/components/prose/colors.js:6]: update: I'm not sure if this will be possible with the current implementation as interpolating values into `url` calls is impossible. Hex codes don't work either.

File: packages/react/src/Prose/Prose.module.css [hunk 3]
```diff
@@ -140,7 +140,7 @@
 
 .Prose ul {
   list-style-type: image;
-  list-style-image: url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' aria-hidden='true' focusable='false' role='img' viewBox='0 -3 16 16' width='16' height='16' fill='currentColor' style='display: inline-block; vertical-align: text-bottom; overflow: visible;'%3e%3cpath d='M2 7.75A.75.75 0 0 1 2.75 7h10a.75.75 0 0 1 0 1.5h-10A.75.75 0 0 1 2 7.75Z'%3e%3c/path%3e%3c/svg%3e ");
+  list-style-image: var(--brand-Prose-imageUrl-default);
```
Comment (rezrah) [inline packages/react/src/Prose/Prose.module.css:143]: This token doesn't mention lists 🤔, and I can't find the previous thread for the previous suggestion.. Could we be a little more specific please?

Could you change this to `--brand-Prose-unorderedList-imageUrl` please. `default` could be interesting for the future, if we add more styles, but perhaps a little redundant in the meantime.

File: packages/react/src/Prose/Prose.stories.tsx [hunk 4]
```diff
@@ -63,7 +64,42 @@ const ExampleHtmlMarkup = `
...
+  darkMode: true,
+}
+UnorderedList.argTypes = {
+  colorMode: {
+    darkMode: 'boolean',
+  },
+}
+UnorderedList.decorators = [
+  (Story, {args: {darkMode}}) => (
+    <>
```
Comment (rezrah) [inline packages/react/src/Prose/Prose.stories.tsx:96]: You can drop the fragment here ☝️

File: packages/react/src/Prose/Prose.stories.tsx [hunk 5]
```diff
@@ -63,7 +64,42 @@ const ExampleHtmlMarkup = `
...
+    Donec at dolor ut metus imperdiet congue vel porta nunc.
+  </li>
+  <li>
+    Quisque eu tortor suscipit, congue quam in, bibendum tellus.
+  </li>
+</ul>
+`
+
+export const Playground: StoryFn = args => <Prose {...args} html={ExampleHtmlMarkup} />
+const UnorderedListStory: StoryFn = args => <Prose {...args} html={UnorderedListHtmlMarkup} />
```
Comment (rezrah) [inline packages/react/src/Prose/Prose.stories.tsx:82]: Could we please move this story to `Prose.features.stories.tsx` so that it appears under `Features` in the nav? The only top-level stories we display should be `Default` and `Playground`. 

Screenshot 2023-10-17 at 10 03 15

**Review by nsolerieu — APPROVED** [review]
DIF and preview looks good to me ✌️

**Review by rezrah — APPROVED** [review]
