### PR TITLE
SubdomainNavBar overflow fix

### LINKED ISSUE #405: [Accessibility] Improve overflowing of `SubdomainNavBar` on mobile
This came up in https://github.com/github/accessibility-audits/issues/5254. The `SubdomainNavBar` on mobile could run into overflow issues (overlapping) when there is not enough height and lots of items. Or in this case when zoomed in to 200%:

An option might be to add some overflow scrolling when the height runs out. But it might be tricky to fix since the extra buttons (at the bottom) are positioned absolutely? 🤔

### PR DESCRIPTION
**Pull request by joseph-lozano**
## Summary

This PR fixes 2 issues:
1. If the sandwich menu was open on narrow screen sizes, and then the viewport was widened, nav items would be duplicated.
2. If there were too many nav items for the height of the viewport, they would overflow into the CTA actions. (#405)

Fixes #405 
## List of notable changes:

The if the Nav menu is open, the background will no longer be scrollable, but the Nav menu will be.

## What should reviewers focus on?

Verify that the SubdomainNavBar is working as intended, and there were no unintended side-effect changes.

## Steps to test:

1. Go to `MobileMenuOpenManyItems` in Storybook and verify that it is working as intended.
1. Verify that it is working as intended.
1. Ensure all other stories are unchanged

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [ ] All developer debugging and non-functional logging has been removed
- [ ] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

> Please try to provide before and after screenshots or videos

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

CleanShot 2023-10-05 at 12 50 22@2x

 </td>
<td valign="top">

CleanShot 2023-10-05 at 12 50 42@2x

</td>
</tr>
</table>

### CODE REVIEW

File: packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx [hunk 1]
```diff
@@ -79,10 +80,22 @@ function Root({
 }: SubdomainNavBarProps) {
   const [menuHidden, setMenuHidden] = useState(true)
   const [searchVisible, setSearchVisible] = useState(false)
+  const {width} = useWindowSize()
 
   const handleMobileMenuClick = () => setMenuHidden(!menuHidden)
   const handleSearchVisibility = () => setSearchVisible(!searchVisible)
 
+  useEffect(() => {
+    if (width && width >= 768) {
```
Comment (rezrah) [inline packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx:89]: Can you use `isMedium` from `useWindowSize` here to avoid hardcoding this breakpoint?

File: packages/react/src/SubdomainNavBar/SubdomainNavBar.stories.tsx [hunk 2]
```diff
@@ -547,6 +549,18 @@ MobileMenuOpen.play = async ({canvasElement}) => {
   await userEvent.click(canvas.getByLabelText('Menu'))
 }
 
+export const MobileMenuOpenManyItems = Template.bind({})
```
Comment (rezrah) [inline packages/react/src/SubdomainNavBar/SubdomainNavBar.stories.tsx:552]: The overflowing buttons regression seems to be cropping out the close button too on this story:

https://primer-cabd91a764-26139705.drafts.github.io/storybook/?path=/story/components-subdomainnavbar--mobile-menu-open-many-items

Screenshot 2023-10-10 at 15 23 37

It doesn't seem to be happening on this story however: 
https://primer-cabd91a764-26139705.drafts.github.io/storybook/?path=/story/components-subdomainnavbar--mobile-menu-open

Possible to take a look into what's happening here please? We can't have the close button being partially out off canvas.

File: packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css [hunk 3]
```diff
@@ -535,7 +545,7 @@
   }
 }
 
-@media screen and (min-width: 48rem) {
+@media screen and (min-width: 767px) {
```
Comment (rezrah) [inline packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css:548]: What was the reason for this change?

FYI, we prefer to use `rem` values for breakpoints... here's the available ones:

Screenshot 2023-10-12 at 09 21 33

File: packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Full-Width-1-linux.png
Comment (rezrah) [inline packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Full-Width-1-linux.png:1]: This would appear to be a regression. Is it related to the fix for mobile menu overflowing? If yes, can we isolate that change to narrow viewports only? And if not, can we back this change out for now please?

**Review by nsolerieu — APPROVED** [review]
The screenshots in the description look good to me from a visual standpoint.
To @rezrah comment, I'd suggest using our breakpoints variables.

File: packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css (hunk 3 above)
Comment (joseph-lozano) [reply packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css:548]: I can drop down to `47.75rem`, but I had to change this to fix a bug where **both** the CTA buttons and the sandwich menu were invisible at exactly `768px`.

Comment (joseph-lozano) [reply packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css:548]: perhaps `calc(var(--brand-breakpoint-medium) - 1px)`?

File: packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Full-Width-1-linux.png
Comment (joseph-lozano) [reply packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Full-Width-1-linux.png:1]: The movement is caused because the CTA buttons are no longer being squashed (see the "longer title" story for a more extreme example of that happening)

File: packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-16bce-le-No-Links-SubdomainNavBar-Mobile-No-Links-1-linux.png
Comment (rezrah) [inline packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-16bce-le-No-Links-SubdomainNavBar-Mobile-No-Links-1-linux.png:1]: @nsolerieu @natalie-iv - FYI due to space constraints, we're proposing to drop the title at the narrowest viewport 👇 

Screenshot 2023-10-24 at 17 34 38

It will reappear again at the next larger breakpoint.

Is this cool with y'all? FYI, we also already have an option to use this pattern without the title, [even at desktop](https://primer-cabd91a764-26139705.drafts.github.io/storybook/?path=/story/components-subdomainnavbar--no-title), so this is building on top of that precedent.

**Review by nsolerieu — APPROVED** [review]
Make sense, shit it 🚀

I think it makes sense considering space/size but we are loosing an important semantic element which my create a bit of confusion... but I don't have a (great) solution to offer.

**Review by rezrah — APPROVED** [review]
LGTM... 

In the words of @nsolerieu, shit it :shipit: 🤣 

Screenshot 2023-10-24 at 18 09 02
