### PR TITLE
Resolves #528 - spread props on HeroDescription

### LINKED ISSUE #528: 🐛 [BUG] - `className` is missing on `<Hero.Description>`
### Describe the bug

It seems not possible to use a `className` on the [`<Hero.Description>`](https://primer.style/brand/components/Hero/react).

### Reproduction steps

1. Go to https://primer.style/brand/components/Hero/react.
2. Paste following example:
    ```JSX
    <Hero className="HeroClass">
      <Hero.Heading className="HeroHeadingClass">Heading</Hero.Heading>
      <Hero.Description className="HeroDescriptionClass">Description</Hero.Description>
    </Hero>
    ```
3. Inspect class names with DevTools.
4. Notice how the `HeroDescriptionClass` is missing on `<Hero.Description>`.

### Expected behavior

`HeroDescriptionClass` should be applied on `<Hero.Description>`.

### Screenshots

_No response_

### Browsers

Chrome

### OS

Mac

### PR DESCRIPTION
**Pull request by alexbuiltit**
## Summary

Minor change that resolves #528 - allowing users to add custom class names to the `HeroDescription` component

## List of notable changes:

- **added** `{...rest}` to `HeroDescription` to allow for custom class names to be used, this pattern is being used in `HeroHeading`, `HeroImage` etc.

## What should reviewers focus on?

One thing to consider is that when a custom class name is being used it will remove the `Hero-description` styles, this is existing behaviour on the `HeroHeading` therefore isn't a regression. 

## Steps to test:

1. Run Storybook
1. Modify the default `Hero.stories.tsx` file and include a `className` on the `HeroDescription` component.
1. Open the Hero story on storybook, inspect element and see class added to the hero description.

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [x] Tests prove that the feature works and covers both happy and unhappy paths
- [x] Any drop in coverage, breaking changes or regressions have been documented above
- [x] New visual snapshots have been generated / updated for any UI changes
- [x] All developer debugging and non-functional logging has been removed
- [x] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

### CODE REVIEW

File: packages/react/src/Hero/Hero.tsx [hunk 1]
```diff
@@ -105,9 +105,9 @@ type HeroDescriptionProps = {
 } & BaseProps<HTMLParagraphElement>
 
 const HeroDescription = forwardRef<HTMLParagraphElement, PropsWithChildren<HeroDescriptionProps>>(
-  ({size = '200', weight, children}: PropsWithChildren<HeroDescriptionProps>, ref) => {
+  ({size = '200', weight, children, ...rest}: PropsWithChildren<HeroDescriptionProps>, ref) => {
     return (
-      <Text ref={ref} className={styles['Hero-description']} as="p" size={size} weight={weight}>
+      <Text ref={ref} className={styles['Hero-description']} as="p" size={size} weight={weight} {...rest}>
```
Comment (rezrah) [inline packages/react/src/Hero/Hero.tsx:110]: > One thing to consider is that when a custom class name is being used it will remove the Hero-description styles, this is existing behaviour on the HeroHeading therefore isn't a regression.

👋 @alexbuiltit - thanks for opening this PR, and drawing our attention to this potential regression ✨. 

To avoid losing the default styles, you could destructure the `className` as an argument before spreading the remaining properties in. The destuctured value can then be passed into a class name concat function (we typically use `clsx`).

Here's an example of how it's done [in another component](https://github.com/primer/brand/blob/main/packages/react/src/Button/Button.tsx#L160). Hope this helps!

Comment (alexbuiltit) [reply packages/react/src/Hero/Hero.tsx:110]: Hey @rezrah!

Okay great, didn't see you were already using `clsx`, I'll make that change today.

Comment (alexbuiltit) [reply packages/react/src/Hero/Hero.tsx]: Not sure how I missed the use of `clsx` given its already being imported in the `Hero` component 🤦

I've pushed the change now and update the changeset.

File: .changeset/dry-news-dress.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@primer/react-brand': patch
+---
+
+Add className to HeroDescription
```
Comment (rezrah) [inline .changeset/dry-news-dress.md:5]:
```suggestion
Added `className` to `Hero.Description`
```

**Review by rezrah — APPROVED** [review]
Thanks for making the update @alexbuiltit. The changes looks good. One minor suggestion for the change log, but otherwise :shipit:

**Comment by alexbuiltit** [comment]
Hey @rezrah I've approved your suggestion, is there anything else I need to do or best to leave it with you/the team for now?

**Comment by rezrah** [comment]
> Hey @rezrah I've approved your suggestion, is there anything else I need to do or best to leave it with you/the team for now?

👍 Thanks for resolving this issue @alexbuiltit, and for contributing to Primer. I'll get this merged for you now.
